2024-10-12 17:01:34,947, WARNING, Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\danil\OneDrive\Рабочий стол\UrbanUniversityHomework\module12\module_12_4\tests_12_4.py", line 72, in test_run
    runner = Runner("Runner", -3)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danil\OneDrive\Рабочий стол\UrbanUniversityHomework\module12\module_12_4\tests_12_4.py", line 15, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -3
2024-10-12 17:01:34,954, WARNING, Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\danil\OneDrive\Рабочий стол\UrbanUniversityHomework\module12\module_12_4\tests_12_4.py", line 60, in test_walk
    runner = Runner(3)
             ^^^^^^^^^
  File "C:\Users\danil\OneDrive\Рабочий стол\UrbanUniversityHomework\module12\module_12_4\tests_12_4.py", line 10, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
